DROP TABLE State
DROP TABLE GrowsIn
DROP TABLE Plant
DROP TABLE ThreatenedPlant
DROP TABLE FloweringPlant
DROP TABLE Non-FloweringPlant
DROP TABLE BotanicalGarden
DROP TABLE FoodPlant
DROP TABLE WaterBody