-- Name: Shreya Wadhwa
-- JHEDID: swadhwa5

SET sql_mode='ANSI_QUOTES';

DROP TABLE IF EXISTS GrowsIn;
DROP TABLE IF EXISTS BotanicalGarden;
DROP TABLE IF EXISTS WaterBody;
DROP TABLE IF EXISTS "State";
DROP TABLE IF EXISTS ThreatenedPlant;
DROP TABLE IF EXISTS FloweringPlant;
DROP TABLE IF EXISTS Plant;